# Generated by Django 4.1.7 on 2023-03-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace_id', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=1000)),
                ('gas_limit', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('height', models.IntegerField(blank=True, null=True)),
                ('txhash', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
